# Generated by Django 4.2.2 on 2023-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyBoard",
            fields=[
                (
                    # 따로 지정하지 않으면 장고가 자동으로 ID를 만들어서 PK로 정함
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myname", models.CharField(max_length=100)),
                ("mytitle", models.CharField(max_length=500)),
                ("mycontent", models.CharField(max_length=2000)),
                ("mydate", models.DateTimeField()),
            ],
        ),
    ]
